apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-demo-ping
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: golang-demo-ping
  template:
    metadata:
      labels:
        app: golang-demo-ping
      annotations:
        apm.datadoghq.com/env: '{ "DD_ENV": "prod", "DD_SERVICE": "golang-demo-ping"}'
        ad.datadoghq.com/app.logs: '[{}]'
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: app
          image: asia-docker.pkg.dev/dtamura-service01/containers/golang-demo-ping:v0.0.3
          ports:
            - containerPort: 3000
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(DD_AGENT_HOST):4318
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "k8s.pod.ip=$(POD_IP),service.name=golang-demo-ping,deployment.environment=prod,service.version=0.0.3"

            - name: PING_TARGET_URL
              value: http://golang-demo-app:80

          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
