apiVersion: v1
kind: Secret
metadata:
  name: oauth-credentials
type: Opaque
data:
    client_id: NzE3NjA2NTExMDc0LTkxa2MwZG45YnRuMG9oOGVtdmthOG04a3VwZTdhMW9vLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
    client_secret: R09DU1BYLTlXYnBlcXhoY2FaeWNqT1lWRjU1cXJwZExXeFE=