apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: golang-demo-ping

build:
  artifacts:
    - image: asia-docker.pkg.dev/dtamura-service01/containers/golang-demo-ping
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - deployments

deploy:
  kubectl: {}
